site_name: HIS4936 Final Project Starter
theme_dir: theme
theme: null
copyright: 'Copyright &copy; 2017 <a href="mailto:dave.a.base@gmail.com">David J. Thomas</a>'
repo_url: https://github.com/thePortus/his4936-starter
repo_name: 'GitHub'
pages:
- Home: 'index.md'
- Some Page: 'some_page.md'
- Credits: 'credits.md'
